### ISSUE TITLE
Execute Make depends in cpp , Error  like  undefined reference to `folly::f14::detail::F14LinkCheck<(folly::f14::detail::F14IntrinsicsMode)1>::check()'

### ISSUE THREAD

**Issue by nelsonspark** [oap-project/Gluten-Trino#11]
when execute make depends , error info below ：

/usr/bin/ld: ../../../lib/libproxygen.a(HTTPSession.cpp.o): in function `folly::f14::detail::F14Table<folly::f14::detail::ValueContainerPolicy<unsigned long, void, void, void, void> >::rehashImpl(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long)':
HTTPSession.cpp:(.text._ZN5folly3f146detail8F14TableINS1_20ValueContainerPolicyImvvvvEEE10rehashImplEmmmmm[_ZN5folly3f146detail8F14TableINS1_20ValueContainerPolicyImvvvvEEE10rehashImplEmmmmm]+0x443): undefined reference to `folly::f14::detail::F14LinkCheck<(folly::f14::detail::F14IntrinsicsMode)1>::check()'
/usr/bin/ld: ../../../lib/libproxygen.a(HTTPSession.cpp.o): in function `folly::f14::detail::F14Table<folly::f14::detail::NodeContainerPolicy<unsigned long, proxygen::HTTPTransaction, void, void, void> >::rehashImpl(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long)':
HTTPSession.cpp:(.text._ZN5folly3f146detail8F14TableINS1_19NodeContainerPolicyImN8proxygen15HTTPTransactionEvvvEEE10rehashImplEmmmmm[_ZN5folly3f146detail8F14TableINS1_19NodeContainerPolicyImN8proxygen15HTTPTransactionEvvvEEE10rehashImplEmmmmm]+0x483): undefined reference to `folly::f14::detail::F14LinkCheck<(folly::f14::detail::F14IntrinsicsMode)1>::check()'
/usr/bin/ld: ../../../lib/libproxygen.a(HeaderTable.cpp.o): in function `folly::f14::detail::F14Table<folly::f14::detail::VectorContainerPolicy<proxygen::HPACKHeaderName, std::__cxx11::list<unsigned int, std::allocator<unsigned int> >, void, void, void, std::integral_constant<bool, true> > >::rehashImpl(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long)':
HeaderTable.cpp:(.text._ZN5folly3f146detail8F14TableINS1_21VectorContainerPolicyIN8proxygen15HPACKHeaderNameENSt7__cxx114listIjSaIjEEEvvvSt17integral_constantIbLb1EEEEE10rehashImplEmmmmm[_ZN5folly3f146detail8F14TableINS1_21VectorContainerPolicyIN8proxygen15HPACKHeaderNameENSt7__cxx114listIjSaIjEEEvvvSt17integral_constantIbLb1EEEEE10rehashImplEmmmmm]+0x63f): undefined reference to `folly::f14::detail::F14LinkCheck<(folly::f14::detail::F14IntrinsicsMode)1>::check()'
collect2: error: ld returned 1 exit status
make[3]: *** [proxygen/httpclient/samples/curl/CMakeFiles/proxygen_curl.dir/build.make:129：proxygen/httpclient/samples/curl/proxygen_curl] 错误 1
make[3]: 离开目录“/home/nelson/gluten_workspace/Gluten-Trino/cpp/_deps/proxygen/antlr4-cpp-runtime-4.9.3-source”
make[2]: *** [CMakeFiles/Makefile2:1499：proxygen/httpclient/samples/curl/CMakeFiles/proxygen_curl.dir/all] 错误 2

**Comment by jikunshang** [comment]
seems this is folly/proxygen dependency build issue, can you provide more details about your OS and hardware?

**Comment by nelsonspark** [comment]
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian

**Comment by nelsonspark** [comment]
> 

thanks , this problem is fixed .
