### ISSUE TITLE
Linking gluten_trino error 

### ISSUE THREAD

**Issue by nelsonspark** [oap-project/Gluten-Trino#12]
OS Info and hardware info:

PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian

架构：                   x86_64
  CPU 运行模式：         32-bit, 64-bit
  Address sizes:         43 bits physical, 48 bits virtual
  字节序：               Little Endian
CPU:                     8
  在线 CPU 列表：        0-7
厂商 ID：                AuthenticAMD
  型号名称：             AMD Ryzen 7 4800H with Radeon Graphics
    CPU 系列：           23
    型号：               96
    每个核的线程数：     1
    每个座的核数：       1
    座：                 8
    步进：               1
    BogoMIPS：           5789.13

Linking error info : 

[362/362] Linking CXX shared library src/libgluten_trino.so
FAILED: src/libgluten_trino.so 
: && /usr/bin/c++ -fPIC -mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2 -O3 -DNDEBUG   -shared -Wl,-soname,libgluten_trino.so -o src/libgluten_trino.so velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/FileHandle.cpp.o velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/HiveConfig.cpp.o velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/HiveConnector.cpp.o velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/HiveDataSink.cpp.o velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/HiveDataSource.cpp.o velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/HivePartitionUtil.cpp.o velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/PartitionIdGenerator.cpp.o velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/TableHandle.cpp.o velox/velox/connectors/tpch/CMakeFiles/velox_tpch_connector.dir/TpchConnector.cpp.o src/protocol/CMakeFiles/trino_protocol.dir/trino_protocol.cpp.o src/protocol/CMakeFiles/trino_protocol.dir/DataSize.cpp.o src/protocol/CMakeFiles/trino_protocol.dir/Duration.cpp.o src/protocol/CMakeFiles/trino_protocol.dir/Base64Util.cpp.o src/types/CMakeFiles/presto_type_converter.dir/PrestoToVeloxQueryPlan.cpp.o src/types/CMakeFiles/presto_type_converter.dir/PrestoToVeloxExpr.cpp.o src/types/CMakeFiles/presto_type_converter.dir/TypeSignatureTypeConverter.cpp.o src/types/CMakeFiles/presto_type_converter.dir/antlr/TypeSignatureParser.cpp.o src/types/CMakeFiles/presto_type_converter.dir/antlr/TypeSignatureLexer.cpp.o src/types/CMakeFiles/presto_type_converter.dir/PrestoToVeloxSplit.cpp.o src/CMakeFiles/gluten_trino.dir/TrinoBridge.cpp.o src/CMakeFiles/gluten_trino.dir/utils.cpp.o src/CMakeFiles/gluten_trino.dir/NativeConfigs.cpp.o src/CMakeFiles/gluten_trino.dir/utils/JniUtils.cpp.o src/CMakeFiles/gluten_trino.dir/TrinoExchangeSource.cpp.o src/CMakeFiles/gluten_trino.dir/utils/HttpClient.cpp.o src/CMakeFiles/gluten_trino.dir/utils/Configs.cpp.o src/CMakeFiles/gluten_trino.dir/__/_deps/simdjson-src/simdjson/singleheader/simdjson.cpp.o  -Wl,-rpath,/usr/local/lib  src/functions/libgluten_trino_functions.a  src/serialization/libgluten_trino_serialization.a  velox/velox/core/libvelox_core.a  velox/velox/vector/libvelox_vector.a  velox/velox/exec/libvelox_exec.a  velox/velox/common/time/libvelox_time.a  velox/velox/type/libvelox_type.a  velox/velox/type/tz/libvelox_type_tz.a  velox/velox/common/serialization/libvelox_serialization.a  velox/velox/common/encode/libvelox_encode.a  velox/velox/dwio/common/exception/libvelox_dwio_common_exception.a  velox/velox/functions/lib/libvelox_functions_lib.a  velox/velox/connectors/hive/libvelox_hive_partition_function.a  velox/velox/functions/prestosql/window/libvelox_window.a  velox/velox/dwio/dwrf/reader/libvelox_dwio_dwrf_reader.a  velox/velox/dwio/parquet/libvelox_dwio_parquet_reader.a  velox/velox/functions/prestosql/registration/libvelox_functions_prestosql.a  velox/velox/functions/prestosql/aggregates/libvelox_aggregates.a  velox/velox/type/fbhive/libvelox_type_fbhive.a  velox/velox/connectors/hive/storage_adapters/hdfs/libvelox_hdfs.a  velox/velox/exec/tests/utils/libvelox_exec_test_lib.a  velox/velox/parse/libvelox_parse_parser.a  velox/velox/parse/libvelox_parse_utils.a  velox/velox/parse/libvelox_parse_expression.a  velox/velox/vector/tests/utils/libvelox_vector_test_lib.a  /usr/local/lib/libproxygenhttpserver.a  /usr/local/lib/libproxygen.a  /usr/local/lib/libwangle.a  /usr/local/lib/libfizz.a  /usr/local/lib/libfmt.a  /usr/local/lib/libfolly.a  /usr/lib/x86_64-linux-gnu/libre2.so  velox/velox/functions/lib/window/libvelox_functions_window.a  velox/velox/functions/prestosql/registration/libvelox_functions_prestosql.a  velox/velox/functions/prestosql/libvelox_functions_prestosql_impl.a  velox/velox/functions/prestosql/json/libvelox_functions_json.a  velox/velox/external/md5/libmd5.a  velox/velox/functions/prestosql/types/libvelox_presto_types.a  velox/velox/functions/lib/libvelox_is_null_functions.a  velox/velox/functions/prestosql/aggregates/libvelox_aggregates.a  velox/velox/functions/lib/libvelox_functions_lib.a  velox/velox/common/hyperloglog/libvelox_common_hyperloglog.a  velox/velox/functions/lib/aggregates/libvelox_functions_aggregates.a  velox/velox/connectors/hive/libvelox_hive_partition_function.a  velox/velox/dwio/dwrf/reader/libvelox_dwio_dwrf_reader.a  velox/velox/dwio/parquet/libvelox_dwio_parquet_reader.a  velox/velox/dwio/parquet/reader/libvelox_dwio_native_parquet_reader.a  velox/velox/dwio/parquet/thrift/libvelox_dwio_parquet_thrift.a  velox/velox/connectors/hive/storage_adapters/hdfs/libvelox_hdfs.a  /usr/local/lib/libhdfs3.so  velox/velox/dwio/catalog/fbhive/libvelox_dwio_catalog_fbhive.a  velox/velox/dwio/parquet/libvelox_dwio_parquet_writer.a  velox/velox/dwio/parquet/writer/libvelox_dwio_arrow_parquet_writer.a  velox/third_party/arrow_ep/install/lib/libparquet.a  velox/third_party/arrow_ep/install/lib/libarrow.a  /usr/local/lib/libthrift.a  velox/velox/connectors/hive/storage_adapters/s3fs/libvelox_s3fs.a  velox/velox/connectors/hive/storage_adapters/gcs/libvelox_gcs.a  velox/velox/exec/libvelox_exec.a  velox/velox/codegen/libvelox_codegen.a  velox/velox/exec/libvelox_exec.a  velox/velox/codegen/libvelox_codegen.a  velox/velox/vector/arrow/libvelox_arrow_bridge.a  velox/velox/serializers/libvelox_presto_serializer.a  velox/velox/row/libvelox_row_fast.a  velox/velox/dwio/dwrf/writer/libvelox_dwio_dwrf_writer.a  velox/velox/dwio/dwrf/common/libvelox_dwio_dwrf_common.a  /usr/lib/x86_64-linux-gnu/libsnappy.so  velox/velox/dwio/dwrf/utils/libvelox_dwio_dwrf_utils.a  velox/velox/dwio/dwrf/proto/libvelox_dwio_dwrf_proto.a  /usr/lib/x86_64-linux-gnu/libprotobuf.so  /usr/lib/x86_64-linux-gnu/libzstd.so  /usr/lib/x86_64-linux-gnu/liblz4.so  /usr/lib/x86_64-linux-gnu/liblzo2.so  /usr/lib/x86_64-linux-gnu/libz.so  velox/velox/exec/tests/utils/libvelox_temp_path.a  velox/velox/dwio/common/tests/utils/libvelox_dwio_common_test_utils.a  velox/velox/type/fbhive/libvelox_type_fbhive.a  velox/velox/dwio/common/libvelox_dwio_common.a  velox/velox/dwio/common/compression/libvelox_dwio_common_compression.a  velox/velox/dwio/common/libvelox_dwio_common.a  velox/velox/dwio/common/compression/libvelox_dwio_common_compression.a  velox/velox/dwio/common/exception/libvelox_dwio_common_exception.a  velox/velox/common/compression/libvelox_common_compression.a  velox/velox/dwio/common/encryption/libvelox_dwio_common_encryption.a  velox/velox/duckdb/conversion/libvelox_duckdb_parser.a  velox/velox/duckdb/conversion/libvelox_duckdb_conversion.a  velox/velox/external/duckdb/tpch/libtpch_extension.a  velox/velox/parse/libvelox_parse_expression.a  velox/velox/parse/libvelox_parse_utils.a  velox/velox/functions/libvelox_function_registry.a  velox/velox/expression/libvelox_expression.a  velox/velox/core/libvelox_core.a  velox/velox/common/caching/libvelox_caching.a  velox/velox/common/file/libvelox_file.a  velox/velox/expression/libvelox_expression_functions.a  velox/velox/expression/type_calculation/libvelox_type_calculation.a  velox/velox/functions/lib/libvelox_functions_util.a  /usr/local/lib/libfmt.a  /usr/lib/x86_64-linux-gnu/libboost_context.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_atomic.so.1.74.0  /usr/lib/x86_64-linux-gnu/libgflags.so.2.2.2  velox/velox/connectors/libvelox_connector.a  velox/velox/core/libvelox_config.a  velox/velox/tpch/gen/libvelox_tpch_gen.a  velox/velox/vector/libvelox_vector.a  velox/velox/common/time/libvelox_time.a  velox/velox/type/libvelox_type.a  velox/velox/type/tz/libvelox_type_tz.a  velox/velox/common/serialization/libvelox_serialization.a  velox/velox/external/date/libvelox_external_date.a  velox/velox/common/encode/libvelox_encode.a  velox/velox/buffer/libvelox_buffer.a  velox/velox/common/memory/libvelox_memory.a  velox/velox/common/testutil/libvelox_test_util.a  velox/velox/common/base/libvelox_common_base.a  velox/velox/common/base/libvelox_exception.a  velox/velox/common/process/libvelox_process.a  /usr/local/lib/libfolly.a  /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.74.0  /usr/local/lib/libfmt.a  /usr/lib/x86_64-linux-gnu/libdouble-conversion.so  /usr/lib/x86_64-linux-gnu/libglog.so  /usr/lib/x86_64-linux-gnu/libevent.so  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libssl.so  /usr/lib/x86_64-linux-gnu/libcrypto.so  /usr/lib/x86_64-linux-gnu/libbz2.so  /usr/lib/x86_64-linux-gnu/liblzma.so  /usr/lib/x86_64-linux-gnu/liblz4.so  /usr/lib/x86_64-linux-gnu/libzstd.so  /usr/lib/x86_64-linux-gnu/libsnappy.so  /usr/lib/x86_64-linux-gnu/libsodium.so  -ldl  /usr/lib/x86_64-linux-gnu/libunwind.so  /usr/lib/x86_64-linux-gnu/libboost_context.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_atomic.so.1.74.0  /usr/lib/x86_64-linux-gnu/libgflags.so.2.2.2  /usr/lib/x86_64-linux-gnu/libglog.so  /usr/lib/x86_64-linux-gnu/libre2.so  /usr/lib/x86_64-linux-gnu/libre2.so  /usr/lib/x86_64-linux-gnu/libgflags.so.2.2.2  -lpthread  lib/libgtest.a  velox/velox/external/duckdb/tpch/dbgen/libdbgen.a  velox/velox/external/duckdb/libduckdb.a  /usr/local/lib/libantlr4-runtime.a  -luuid && :
/usr/bin/ld: /usr/local/lib/libthrift.a(TBufferTransports.o): warning: relocation against `_ZN6apache6thrift9transport19TTransportExceptionD1Ev' in read-only section `.text._ZN6apache6thrift9transport17TVirtualTransportINS1_16TFramedTransportENS1_11TBufferBaseEE12consume_virtEj[_ZN6apache6thrift9transport17TVirtualTransportINS1_16TFramedTransportENS1_11TBufferBaseEE12consume_virtEj]'
/usr/bin/ld: /usr/local/lib/libthrift.a(TProtocol.o): relocation R_X86_64_PC32 against symbol `_ZTVN6apache6thrift8protocol9TProtocolE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: 最后的链结失败: bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Actions : 
cpp/src/CMakeLists.txt  target_link_libraries(gluten_trino PUBLIC ${FMT} Folly::folly ${RE2}
                                          presto_type_converter )    change to  target_link_libraries(gluten_trino PUBLIC ${FMT} Folly::folly ${RE2}
                                          presto_type_converter PRIVATE "-no-pie")   

Error After do Actions:

FAILED: src/libgluten_trino.so 
: && /usr/bin/c++ -fPIC -mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2 -O3 -DNDEBUG   -shared -Wl,-soname,libgluten_trino.so -o src/libgluten_trino.so velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/FileHandle.cpp.o velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/HiveConfig.cpp.o velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/HiveConnector.cpp.o velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/HiveDataSink.cpp.o velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/HiveDataSource.cpp.o velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/HivePartitionUtil.cpp.o velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/PartitionIdGenerator.cpp.o velox/velox/connectors/hive/CMakeFiles/velox_hive_connector.dir/TableHandle.cpp.o velox/velox/connectors/tpch/CMakeFiles/velox_tpch_connector.dir/TpchConnector.cpp.o src/protocol/CMakeFiles/trino_protocol.dir/trino_protocol.cpp.o src/protocol/CMakeFiles/trino_protocol.dir/DataSize.cpp.o src/protocol/CMakeFiles/trino_protocol.dir/Duration.cpp.o src/protocol/CMakeFiles/trino_protocol.dir/Base64Util.cpp.o src/types/CMakeFiles/presto_type_converter.dir/PrestoToVeloxQueryPlan.cpp.o src/types/CMakeFiles/presto_type_converter.dir/PrestoToVeloxExpr.cpp.o src/types/CMakeFiles/presto_type_converter.dir/TypeSignatureTypeConverter.cpp.o src/types/CMakeFiles/presto_type_converter.dir/antlr/TypeSignatureParser.cpp.o src/types/CMakeFiles/presto_type_converter.dir/antlr/TypeSignatureLexer.cpp.o src/types/CMakeFiles/presto_type_converter.dir/PrestoToVeloxSplit.cpp.o src/CMakeFiles/gluten_trino.dir/TrinoBridge.cpp.o src/CMakeFiles/gluten_trino.dir/utils.cpp.o src/CMakeFiles/gluten_trino.dir/NativeConfigs.cpp.o src/CMakeFiles/gluten_trino.dir/utils/JniUtils.cpp.o src/CMakeFiles/gluten_trino.dir/TrinoExchangeSource.cpp.o src/CMakeFiles/gluten_trino.dir/utils/HttpClient.cpp.o src/CMakeFiles/gluten_trino.dir/utils/Configs.cpp.o src/CMakeFiles/gluten_trino.dir/__/_deps/simdjson-src/simdjson/singleheader/simdjson.cpp.o  -Wl,-rpath,/usr/local/lib  src/functions/libgluten_trino_functions.a  src/serialization/libgluten_trino_serialization.a  velox/velox/core/libvelox_core.a  velox/velox/vector/libvelox_vector.a  velox/velox/exec/libvelox_exec.a  velox/velox/common/time/libvelox_time.a  velox/velox/type/libvelox_type.a  velox/velox/type/tz/libvelox_type_tz.a  velox/velox/common/serialization/libvelox_serialization.a  velox/velox/common/encode/libvelox_encode.a  velox/velox/dwio/common/exception/libvelox_dwio_common_exception.a  velox/velox/functions/lib/libvelox_functions_lib.a  velox/velox/connectors/hive/libvelox_hive_partition_function.a  velox/velox/functions/prestosql/window/libvelox_window.a  velox/velox/dwio/dwrf/reader/libvelox_dwio_dwrf_reader.a  velox/velox/dwio/parquet/libvelox_dwio_parquet_reader.a  velox/velox/functions/prestosql/registration/libvelox_functions_prestosql.a  velox/velox/functions/prestosql/aggregates/libvelox_aggregates.a  velox/velox/type/fbhive/libvelox_type_fbhive.a  velox/velox/connectors/hive/storage_adapters/hdfs/libvelox_hdfs.a  velox/velox/exec/tests/utils/libvelox_exec_test_lib.a  velox/velox/parse/libvelox_parse_parser.a  velox/velox/parse/libvelox_parse_utils.a  velox/velox/parse/libvelox_parse_expression.a  velox/velox/vector/tests/utils/libvelox_vector_test_lib.a  /usr/local/lib/libproxygenhttpserver.a  /usr/local/lib/libproxygen.a  /usr/local/lib/libwangle.a  /usr/local/lib/libfizz.a  /usr/local/lib/libfmt.a  /usr/local/lib/libfolly.a  /usr/lib/x86_64-linux-gnu/libre2.so  -no-pie  velox/velox/functions/lib/window/libvelox_functions_window.a  velox/velox/functions/prestosql/registration/libvelox_functions_prestosql.a  velox/velox/functions/prestosql/libvelox_functions_prestosql_impl.a  velox/velox/functions/prestosql/json/libvelox_functions_json.a  velox/velox/external/md5/libmd5.a  velox/velox/functions/prestosql/types/libvelox_presto_types.a  velox/velox/functions/lib/libvelox_is_null_functions.a  velox/velox/functions/prestosql/aggregates/libvelox_aggregates.a  velox/velox/functions/lib/libvelox_functions_lib.a  velox/velox/common/hyperloglog/libvelox_common_hyperloglog.a  velox/velox/functions/lib/aggregates/libvelox_functions_aggregates.a  velox/velox/connectors/hive/libvelox_hive_partition_function.a  velox/velox/dwio/dwrf/reader/libvelox_dwio_dwrf_reader.a  velox/velox/dwio/parquet/libvelox_dwio_parquet_reader.a  velox/velox/dwio/parquet/reader/libvelox_dwio_native_parquet_reader.a  velox/velox/dwio/parquet/thrift/libvelox_dwio_parquet_thrift.a  velox/velox/connectors/hive/storage_adapters/hdfs/libvelox_hdfs.a  /usr/local/lib/libhdfs3.so  velox/velox/dwio/catalog/fbhive/libvelox_dwio_catalog_fbhive.a  velox/velox/dwio/parquet/libvelox_dwio_parquet_writer.a  velox/velox/dwio/parquet/writer/libvelox_dwio_arrow_parquet_writer.a  velox/third_party/arrow_ep/install/lib/libparquet.a  velox/third_party/arrow_ep/install/lib/libarrow.a  /usr/local/lib/libthrift.a  velox/velox/connectors/hive/storage_adapters/s3fs/libvelox_s3fs.a  velox/velox/connectors/hive/storage_adapters/gcs/libvelox_gcs.a  velox/velox/exec/libvelox_exec.a  velox/velox/codegen/libvelox_codegen.a  velox/velox/exec/libvelox_exec.a  velox/velox/codegen/libvelox_codegen.a  velox/velox/vector/arrow/libvelox_arrow_bridge.a  velox/velox/serializers/libvelox_presto_serializer.a  velox/velox/row/libvelox_row_fast.a  velox/velox/dwio/dwrf/writer/libvelox_dwio_dwrf_writer.a  velox/velox/dwio/dwrf/common/libvelox_dwio_dwrf_common.a  /usr/lib/x86_64-linux-gnu/libsnappy.so  velox/velox/dwio/dwrf/utils/libvelox_dwio_dwrf_utils.a  velox/velox/dwio/dwrf/proto/libvelox_dwio_dwrf_proto.a  /usr/lib/x86_64-linux-gnu/libprotobuf.so  /usr/lib/x86_64-linux-gnu/libzstd.so  /usr/lib/x86_64-linux-gnu/liblz4.so  /usr/lib/x86_64-linux-gnu/liblzo2.so  /usr/lib/x86_64-linux-gnu/libz.so  velox/velox/exec/tests/utils/libvelox_temp_path.a  velox/velox/dwio/common/tests/utils/libvelox_dwio_common_test_utils.a  velox/velox/type/fbhive/libvelox_type_fbhive.a  velox/velox/dwio/common/libvelox_dwio_common.a  velox/velox/dwio/common/compression/libvelox_dwio_common_compression.a  velox/velox/dwio/common/libvelox_dwio_common.a  velox/velox/dwio/common/compression/libvelox_dwio_common_compression.a  velox/velox/dwio/common/exception/libvelox_dwio_common_exception.a  velox/velox/common/compression/libvelox_common_compression.a  velox/velox/dwio/common/encryption/libvelox_dwio_common_encryption.a  velox/velox/duckdb/conversion/libvelox_duckdb_parser.a  velox/velox/duckdb/conversion/libvelox_duckdb_conversion.a  velox/velox/external/duckdb/tpch/libtpch_extension.a  velox/velox/parse/libvelox_parse_expression.a  velox/velox/parse/libvelox_parse_utils.a  velox/velox/functions/libvelox_function_registry.a  velox/velox/expression/libvelox_expression.a  velox/velox/core/libvelox_core.a  velox/velox/common/caching/libvelox_caching.a  velox/velox/common/file/libvelox_file.a  velox/velox/expression/libvelox_expression_functions.a  velox/velox/expression/type_calculation/libvelox_type_calculation.a  velox/velox/functions/lib/libvelox_functions_util.a  /usr/local/lib/libfmt.a  /usr/lib/x86_64-linux-gnu/libboost_context.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_atomic.so.1.74.0  /usr/lib/x86_64-linux-gnu/libgflags.so.2.2.2  velox/velox/connectors/libvelox_connector.a  velox/velox/core/libvelox_config.a  velox/velox/tpch/gen/libvelox_tpch_gen.a  velox/velox/vector/libvelox_vector.a  velox/velox/common/time/libvelox_time.a  velox/velox/type/libvelox_type.a  velox/velox/type/tz/libvelox_type_tz.a  velox/velox/common/serialization/libvelox_serialization.a  velox/velox/external/date/libvelox_external_date.a  velox/velox/common/encode/libvelox_encode.a  velox/velox/buffer/libvelox_buffer.a  velox/velox/common/memory/libvelox_memory.a  velox/velox/common/testutil/libvelox_test_util.a  velox/velox/common/base/libvelox_common_base.a  velox/velox/common/base/libvelox_exception.a  velox/velox/common/process/libvelox_process.a  /usr/local/lib/libfolly.a  /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.74.0  /usr/local/lib/libfmt.a  /usr/lib/x86_64-linux-gnu/libdouble-conversion.so  /usr/lib/x86_64-linux-gnu/libglog.so  /usr/lib/x86_64-linux-gnu/libevent.so  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libssl.so  /usr/lib/x86_64-linux-gnu/libcrypto.so  /usr/lib/x86_64-linux-gnu/libbz2.so  /usr/lib/x86_64-linux-gnu/liblzma.so  /usr/lib/x86_64-linux-gnu/liblz4.so  /usr/lib/x86_64-linux-gnu/libzstd.so  /usr/lib/x86_64-linux-gnu/libsnappy.so  /usr/lib/x86_64-linux-gnu/libsodium.so  -ldl  /usr/lib/x86_64-linux-gnu/libunwind.so  /usr/lib/x86_64-linux-gnu/libboost_context.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_atomic.so.1.74.0  /usr/lib/x86_64-linux-gnu/libgflags.so.2.2.2  /usr/lib/x86_64-linux-gnu/libglog.so  /usr/lib/x86_64-linux-gnu/libre2.so  /usr/lib/x86_64-linux-gnu/libre2.so  /usr/lib/x86_64-linux-gnu/libgflags.so.2.2.2  -lpthread  lib/libgtest.a  velox/velox/external/duckdb/tpch/dbgen/libdbgen.a  velox/velox/external/duckdb/libduckdb.a  /usr/local/lib/libantlr4-runtime.a  -luuid && :
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by jikunshang** [comment]
I would suggest to re-compile thrift library with `-fPIC` option. And I suggest to use g++ 11.4.

**Comment by nelsonspark** [comment]
> I would suggest to re-compile thrift library with `-fPIC` option. And I suggest to use g++ 11.4.

Gluten-Trino/cpp/scripts/setup-helper-functions.sh  

already add  -fPIC , code like '-DCMAKE_POSITION_INDEPENDENT_CODE=ON'

cmake -Wno-dev -B"${BINARY_DIR}" \
    -GNinja \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \       
    -DCMAKE_CXX_STANDARD=17 \
    "${INSTALL_PREFIX+-DCMAKE_PREFIX_PATH=}${INSTALL_PREFIX-}" \
    "${INSTALL_PREFIX+-DCMAKE_INSTALL_PREFIX=}${INSTALL_PREFIX-}" \
    -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS" \
    -DBUILD_TESTING=OFF \
    "$@"

then  error already occur :
/usr/bin/ld: /usr/local/lib/libthrift.a(TBufferTransports.o): warning: relocation against _ZN6apache6thrift9transport19TTransportExceptionD1Ev' in read-only section .text._ZN6apache6thrift9transport17TVirtualTransportINS1_16TFramedTransportENS1_11TBufferBaseEE12consume_virtEj[_ZN6apache6thrift9transport17TVirtualTransportINS1_16TFramedTransportENS1_11TBufferBaseEE12consume_virtEj]'
/usr/bin/ld: /usr/local/lib/libthrift.a(TProtocol.o): relocation R_X86_64_PC32 against symbol `_ZTVN6apache6thrift8protocol9TProtocolE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: 最后的链结失败: bad value

**Comment by nelsonspark** [comment]
> I would suggest to re-compile thrift library with `-fPIC` option. And I suggest to use g++ 11.4.

how to config in Gluten-Trino project souce , to config compile thrift library with -fPIC option ?

**Comment by nelsonspark** [comment]
> I would suggest to re-compile thrift library with `-fPIC` option. And I suggest to use g++ 11.4.

when linking use  /usr/local/lib/libthrift.a  , while fbthrift generator files below :

   1446836  9月  4 16:50 /usr/local/lib/libthriftannotation.a
    445128  9月  4 16:50 /usr/local/lib/libthrifttyperep.a
   1216710  9月  4 16:50 /usr/local/lib/libthriftmetadata.a
    338326  9月  4 16:51 /usr/local/lib/libthrifttype.a
    127648  9月  4 16:51 /usr/local/lib/libthriftanyrep.a
   1431360  9月  4 16:51 /usr/local/lib/libthriftprotocol.a
    311088  9月  4 16:51 /usr/local/lib/libthriftfrozen2.a
  18802314  9月  4 16:53 /usr/local/lib/libthriftcpp2.a

**Comment by jikunshang** [comment]
seems the script will not compile and install `libthrift.a`, can you try `apt-get install -y libthrift-dev` and recompile?

**Comment by jikunshang** [comment]
not sure about where `/usr/local/lib/libthrift.a` is from. can you remove it

**Comment by nelsonspark** [comment]
> not sure about where `/usr/local/lib/libthrift.a` is from. can you remove it


Thanks very much,  re compile thrift with -fPIC  can fix this problem .
