### ISSUE TITLE
Do we have plan to support  compile in Ubuntu , but run in other os (such as CentOS ) 

### ISSUE THREAD

**Issue by nelsonspark** [oap-project/Gluten-Trino#15]
use libgluten-trino.so cross platform may cause many problems , such as  compile in Ubuntu , run in CentOS does't work ，

ldd libgluten_trino.so 

./libgluten_trino.so: /lib64/libgcc_s.so.1: version `GCC_7.0.0' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by ./libgluten_trino.so)
./libgluten_trino.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./libgluten_trino.so)
	linux-vdso.so.1 =>  (0x00007ffcd0fef000)
	libre2.so.9 => not found
	libhdfs3.so.1 => not found
	libsnappy.so.1 => /lib64/libsnappy.so.1 (0x00007f94746a7000)
	libprotobuf.so.32 => not found
	libzstd.so.1 => not found
	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f9474498000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f9474282000)
	libboost_context.so.1.74.0 => not found
	libboost_regex.so.1.74.0 => not found
	libgflags.so.2.2 => not found
	libglog.so.0 => not found
	libevent-2.1.so.7 => not found
	libssl.so.3 => not found
	libcrypto.so.3 => not found
	libbz2.so.1.0 => not found
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f947405c000)
	libunwind.so.8 => not found
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f9473d54000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9473a52000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f947383c000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f947346e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f947bdf6000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9473252000)

Do we have plan to fix this situation recently  ?

**Comment by jikunshang** [comment]
I don't think any c++ library would suggest such behavior (build and run in different linux OS/distrbution, cause dependency libraries may be various). BKM should be build and run on same OS. 
As for CentOS support, we may kick off one or two months later. If you have to run on centos, you can refer how velox and presto-native dependency installed, gluten-trino use same dependency.

**Comment by nelsonspark** [comment]
> 

ok
