### ISSUE TITLE
Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)

### ISSUE THREAD

**Issue by ImTangYun** [oap-project/Gluten-Trino#39]
When I run command make depends，I get follow error

++ echo -n '-mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2 '
+ COMPILER_FLAGS='-mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2 '
+ cmake -Wno-dev -B_build -GNinja -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_CXX_STANDARD=17 '' '' '-DCMAKE_CXX_FLAGS=-mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2 ' -DBUILD_TESTING=OFF
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- checking compiler: GCC (9.3.)
-- Looking for dladdr
-- Looking for dladdr - not found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- adding c++0x support for gcc compiler
-- Checking whether strerror_r returns an int
-- Checking whether strerror_r returns an int -- no
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindLibXml2.cmake:92 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:21 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/data1/tangyun/gluten-trino/Gluten-Trino/cpp/_deps/hawq/depends/libhdfs3/_build/CMakeFiles/CMakeOutput.log".
See also "/data1/tangyun/gluten-trino/Gluten-Trino/cpp/_deps/hawq/depends/libhdfs3/_build/CMakeFiles/CMakeError.log".

real    0m19.367s
user    0m13.873s
sys     0m2.389s
make: *** [Makefile:28: depends] Error 1

what is the problem？ need i install LibXml2 in ubuntu 20.2 by hand？

**Comment by wuxueyang96** [comment]
Yes, you should install libxml2 in your building environment through `sudo apt-get install libxml2-dev`.

**Comment by ImTangYun** [comment]
> Yes, you should install libxml2 in your building environment through `sudo apt-get install libxml2-dev`.

Thanks, after run sudo apt-get install libxml2-dev I ran make depends success
But when I ran make release, I got error:

-- Checking for module 'thrift'
--   No package 'thrift' found
-- Could NOT find Thrift (missing: THRIFT_LIB THRIFT_INCLUDE_DIR) (found version "")
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_INCLUDE_PATH
  JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) (Required is at least version
  "17")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindJNI.cmake:372 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:15 (find_package)


Shold I install thrift  in ubuntu 20.2 by hand？

**Comment by wuxueyang96** [comment]
> > Yes, you should install libxml2 in your building environment through `sudo apt-get install libxml2-dev`.
> 
> Thanks, after run sudo apt-get install libxml2-dev I ran make depends success But when I ran make release, I got error:
> 
> -- Checking for module 'thrift' -- No package 'thrift' found -- Could NOT find Thrift (missing: THRIFT_LIB THRIFT_INCLUDE_DIR) (found version "") CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message): Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) (Required is at least version "17") Call Stack (most recent call first): /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE) /usr/share/cmake-3.16/Modules/FindJNI.cmake:372 (FIND_PACKAGE_HANDLE_STANDARD_ARGS) src/CMakeLists.txt:15 (find_package)
> 
> Should I install thrift in ubuntu 20.2 by hand？

No, you don't need to install thrift by yourself. But it's okay if you want to install it. The root cause is that you need to install a JDK whose version should be higher than 17.
