### ISSUE TITLE
Missing compiled tags

### ISSUE THREAD

**Issue by tianyouyangying** [oap-project/Gluten-Trino#42]
There are currently no compiled packages available to run

**Comment by jikunshang** [comment]
Do you mean this repo didn't provide a binary so file? If so, I think this may not make sense since gluten_trino cpp binary have a lot dependencies that we can not guarantee the provided binary could run smoothly on user side.

**Comment by jikunshang** [comment]
we will do such package when we are ready to release. 
As for now, you can download CI artifacts as an alternative. see https://github.com/oap-project/Gluten-Trino/actions/runs/6243327496

**Comment by tianyouyangying** [comment]
Thanks
