### ISSUE TITLE
Aggregate function signature is not supported: trino.bridge.sum(DECIMAL(15,2))

### ISSUE THREAD

**Issue by nelsonspark** [oap-project/Gluten-Trino#45]
table SQL :

 CREATE TABLE hive.tpch_hive_orc.lineitem ( 
    l_orderkey bigint,                      
    l_partkey integer,                      
    l_suppkey integer,                      
    l_linenumber integer,                   
    l_quantity decimal(15, 2),              
    l_extendedprice decimal(15, 2),         
    l_discount decimal(15, 2),              
    l_tax decimal(15, 2),                   
    l_returnflag varchar(1),                
    l_linestatus varchar(1),                
    l_shipdate date,                        
    l_commitdate date,                      
    l_receiptdate date,                     
    l_shipinstruct varchar(25),             
    l_shipmode varchar(10),                 
    l_comment varchar(44)                   
 )                                          
 WITH (                                     
    format = 'ORC',                         
    textfile_field_separator = '|'          
 ) 

Query SQL:

select
  l_returnflag,
  l_linestatus,
  sum(l_quantity) as sum_qty,
  sum(l_extendedprice) as sum_base_price,
  sum(l_extendedprice * (1 - l_discount)) as sum_disc_price,
  sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge,
  avg(l_quantity) as avg_qty,
  avg(l_extendedprice) as avg_price,
  avg(l_discount) as avg_disc,
  count(*) as count_order
from
  lineitem
where
  l_shipdate <= date '1998-12-01' - interval '90' day
group by
  l_returnflag,
  l_linestatus
order by
  l_returnflag,
  l_linestatus;

Error Msg:

Query 20230919_033200_00041_mvsq6 failed: Exception: VeloxUserError
Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: Aggregate function signature is not supported: trino.bridge.sum(DECIMAL(15,2)). Supported signatures: (real) -> row(double,bigint) -> real, (double) -> row(double,bigint) -> double, (tinyint) -> row(bigint,bigint) -> bigint, (smallint) -> row(bigint,bigint) -> bigint, (integer) -> row(bigint,bigint) -> bigint, (bigint) -> row(bigint,bigint) -> bigint.
Retriable: False
Function: intermediateType
File: ../velox/velox/exec/Aggregate.cpp
Line: 267
Stack trace:

**Comment by mxdzs0612** [comment]
We are still working on decimal agg functions, better to use double currently.

BTW, we haven't test on ORC files, PARQUET is preferred.

**Comment by wuxueyang96** [comment]
We haven't supported sum aggregation for decimal type yet. To test this project, You could modify all decimal types to double types. Or maybe you can make a pull request to help us to support that. Thanks.

**Comment by jikunshang** [comment]
We have fix decimal type aggregation functions(sum/avg) in PR#54. Please have a try :)
