### ISSUE TITLE
Reword misleading title

### ISSUE THREAD

**Issue by mosabua** [oap-project/Gluten-Trino#46]
The title in the readme claims that Trino performance can be doubled with Gluten Trino. This is misleading since Velox only supports x86 processors and only the Hive connector. Performance gains will vary widely with deployment characteristics and workload. The version of Trino used in Gluten Trino is also outdated.

**Comment by jikunshang** [comment]
Thanks for your suggestion, updated readme.

**Comment by mosabua** [comment]
Thank you. Btw.. it might be worth meeting and talking about your efforts and Project Hummingbird in the Trino project and any collaboration with Intel and/or Alibaba on performance related PRs. 

https://github.com/trinodb/trino/issues/14237
