### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/root/trino/client/trino-client/src/main/java/io/trino/client/ErrorLocation.java'

### ISSUE THREAD

**Issue by ImTangYun** [oap-project/Gluten-Trino#49]
When i ran make release, I met error:

[343/368] Generating ../../../src/protocol/trino_protocol.cpp, ../../../src/protocol/trino_protocol.h
make[2]: Entering directory '/data1/user/gluten-trino/Gluten-Trino/cpp/src/protocol'
./java-to-struct-json.py special/*.java special/*.inc  -j | jq . > trino_protocol.json
Traceback (most recent call last):
  File "./java-to-struct-json.py", line 379, in <module>
    sys.exit(main())
  File "./java-to-struct-json.py", line 365, in main
    process_file(file, config, lang, subclasses, classes, depends)
  File "./java-to-struct-json.py", line 193, in process_file
    for line in preprocess_file(filepath):
  File "./java-to-struct-json.py", line 85, in preprocess_file
    text = util.file_read(filename)
  File "/data1/user/gluten-trino/Gluten-Trino/cpp/src/protocol/util.py", line 93, in file_read
    with open(filename) as file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/trino/client/trino-client/src/main/java/io/trino/client/ErrorLocation.java'

It seems a needed java file did not exists?

**Comment by wuxueyang96** [comment]
It seems like you need to specify a `TRINO_HOME` in your environment before you start building this project. The `TRINO_HOME` variable is represented for the path of Trino's source code.

**Comment by ImTangYun** [comment]
> It seems like you need to specify a `TRINO_HOME` in your environment before you start building this project. The `TRINO_HOME` variable is represented for the path of Trino's source code.

I had tried to export TRINO_HOME, but this problem appears the same

**Comment by wuxueyang96** [comment]
> > It seems like you need to specify a `TRINO_HOME` in your environment before you start building this project. The `TRINO_HOME` variable is represented for the path of Trino's source code.
> 
> I had tried to export TRINO_HOME, but this problem appears the same

What's the `TRINO_HOME`, and what version is your trino?

**Comment by ImTangYun** [comment]
> > > It seems like you need to specify a `TRINO_HOME` in your environment before you start building this project. The `TRINO_HOME` variable is represented for the path of Trino's source code.
> > 
> > 
> > I had tried to export TRINO_HOME, but this problem appears the same
> 
> What's the `TRINO_HOME`, and what version is your trino?

![image](https://github.com/oap-project/Gluten-Trino/assets/5945486/2fe5af3f-2d26-4fbb-9cfe-c6c8466a71f3)

I use trino 411 version

**Comment by jikunshang** [comment]
seems you are using root user and `TRINO_HOME` is changed to `/root/trino/`

**Comment by ImTangYun** [comment]
> seems you are using root user and `TRINO_HOME` is changed to `/root/trino‘
It seems to be the key problem
