### ISSUE TITLE
java.lang.IllegalStateException: Unable to load cache item

### ISSUE THREAD

**Issue by ImTangYun** [oap-project/Gluten-Trino#50]
When I try to build java code with command ‘mvn clean package -DskipTests=True -Dair.check.skip-duplicate-finder=True‘
I got error：
[ERROR] Error executing Maven.
[ERROR] java.lang.IllegalStateException: Unable to load cache item
[ERROR] Caused by: Unable to load cache item
[ERROR] Caused by: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper

Any suggestion？

**Comment by ImTangYun** [comment]
I solved this problem by upgrade maven to newest version

**Comment by jikunshang** [comment]
close since user resolved.
