### ISSUE TITLE
1) Configuration property 'gluten-trino.plugin.dir' was not used 2) Configuration property 'query.launch-native-engine' was not used

### ISSUE THREAD

**Issue by ImTangYun** [oap-project/Gluten-Trino#53]
After the step：
![image](https://github.com/oap-project/Gluten-Trino/assets/5945486/2ad18228-d779-4943-adb6-0c5a0cebfe5b)

When I start trino， I got error below：

2023-09-22T17:45:54.009+0800    ERROR   main    io.trino.server.Server  Configuration is invalid

Errors:

1) Configuration property 'gluten-trino.plugin.dir' was not used
2) Configuration property 'query.launch-native-engine' was not used

==========

Do you have any idea why？

**Comment by wuxueyang96** [comment]
How do you modify the `launcher.py`?

**Comment by ImTangYun** [comment]
> How do you modify the `launcher.py`?
I added this:
![image](https://github.com/oap-project/Gluten-Trino/assets/5945486/1e68432e-29db-4484-868c-cbc734615b8b)

**Comment by wuxueyang96** [comment]
Did you write `/data1/.../Gluten-Trino-411.jar;`? I suppose maybe it will be `/data1/.../Gluten-Trino-411.jar:`.

**Comment by ImTangYun** [comment]
> Did you write `/data1/.../Gluten-Trino-411.jar;`? I suppose maybe it will be `/data1/.../Gluten-Trino-411.jar:`.

It seems not work, error is the same

**Comment by wuxueyang96** [comment]
> > Did you write `/data1/.../Gluten-Trino-411.jar;`? I suppose maybe it will be `/data1/.../Gluten-Trino-411.jar:`.
> 
> It seems not work, error is the same

Here are some points:
1. Make sure the path you specified exists.
2. The document didn't mention it but you need to modify the Coordinator's environment.
3. I'm not sure but if `libgluten_trino.so` can't find its dependencies, some classes might not be loaded successfully. You could check it by executing `ldd libgluten_trino.so`, if there is any 'Not Found', it might be this case.

**Comment by ImTangYun** [comment]
> > > Did you write `/data1/.../Gluten-Trino-411.jar;`? I suppose maybe it will be `/data1/.../Gluten-Trino-411.jar:`.
> > 
> > 
> > It seems not work, error is the same
> 
> Here are some points:
> 
> 1. Make sure the path you specified exists.
> 2. The document didn't mention it but you need to modify the Coordinator's environment.
> 3. I'm not sure but if `libgluten_trino.so` can't find its dependencies, some classes might not be loaded successfully. You could check it by executing `ldd libgluten_trino.so`, if there is any 'Not Found', it might be this case.

Thanks！ I will check those
