### ISSUE TITLE
 end index (-3) must not be negative

### ISSUE THREAD

**Issue by ImTangYun** [oap-project/Gluten-Trino#56]
when I ran very simple query（select 1）， I got：
![image](https://github.com/oap-project/Gluten-Trino/assets/5945486/5517dbc5-e4e6-4c46-bdab-278b62d68aeb)

Is there any query can be success？

**Comment by jikunshang** [comment]
Sorry, I didn't reproduce the result on my side. Can you try use hive or tpch connector to run a simple query?
![image](https://github.com/oap-project/Gluten-Trino/assets/50897707/b4d71835-8054-4e1f-ab6f-408f3a7db6d8)

**Comment by ImTangYun** [comment]
> Sorry, I didn't reproduce the result on my side. Can you try use hive or tpch connector to run a simple query? ![image](https://user-images.githubusercontent.com/50897707/270230283-b4d71835-8054-4e1f-ab6f-408f3a7db6d8.png)

Strange problem， Can you tell me where libgluten_trino.so you put？
/lib/ or/usr/lib?

**Comment by jikunshang** [comment]
I am using ubuntu 22.04. I put it into `/lib64/` dir. I feel `/lib/` should also work.

**Comment by ImTangYun** [comment]
> I am using ubuntu 22.04. I put it into `/lib64/` dir. I feel `/lib/` should also work.

Thnks, I will try
